options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd stream-service
      gcloud functions deploy firestore-to-bigquery-stream-service \
      --entry-point=main \
      --gen2 \
      --runtime python38 \
      --region us-central1 \
      --trigger-location=us-central1 \
      --trigger-event-filters=type=google.cloud.firestore.document.v1.written \
      --trigger-event-filters=database='porfin' \
      --trigger-event-filters-path-pattern=document='person/{person}' \
      --source .
