options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firestore-to-bigquery-batch-service', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/firestore-to-bigquery-batch-service' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'firestore-to-bigquery-batch-service'
      - '--image=gcr.io/$PROJECT_ID/firestore-to-bigquery-batch-service'
      - '--platform=managed'
      - '--region=us-central1'
      - '--no-allow-unauthenticated'
      - '--cpu=1'
      - '--memory=1Gi'
      - '--timeout=10m'
      - '--max-instances=1'